import { defineSlotRecipe } from '@chakra-ui/react'

// Site-specific chrome lives in the theme. Components keep content, behavior,
// and one-off layout props; Chakra's css prop consumes these slot recipes.
export const siteSlotRecipes = {
  siteNavbar: defineSlotRecipe({
    slots: ['root', 'container', 'brand', 'navLink', 'githubTrigger'],
    base: {
      root: {
        position: 'sticky',
        top: 0,
        zIndex: 'siteHeader',
        h: 'siteHeader',
        borderBottomWidth: '1px',
        bg: 'bg',
      },
      container: { maxW: '7xl', h: 'full' },
      brand: {
        fontWeight: 'medium',
        fontSize: 'lg',
        _hover: { textDecoration: 'none' },
      },
      navLink: { color: 'fg.muted', _hover: { color: 'fg' } },
      githubTrigger: {
        color: 'fg.muted',
        minH: 11,
        minW: 11,
        _hover: { color: 'fg', bg: 'bg.panel' },
      },
    },
  }),
  siteFooter: defineSlotRecipe({
    slots: ['root', 'container', 'content', 'creditLink', 'licenseLink'],
    base: {
      root: {
        bg: 'bg',
        color: 'fg.muted',
        borderTopWidth: '1px',
        borderColor: 'border',
      },
      container: { maxW: '7xl', py: { base: 6, md: 8 } },
      content: {
        display: 'flex',
        flexDirection: { base: 'column', md: 'row' },
        alignItems: { base: 'flex-start', md: 'center' },
        justifyContent: 'space-between',
        gap: 3,
        fontSize: 'sm',
      },
      creditLink: { color: 'fg' },
      licenseLink: { color: 'fg', minH: 11, flexShrink: 0 },
    },
  }),
  communeFooter: defineSlotRecipe({
    slots: ['root', 'content', 'label', 'link', 'wordmark'],
    base: {
      root: {
        maxW: 'full',
        bg: 'black',
        color: 'white',
        pt: { base: 2, md: 8 },
        pb: { base: 4, md: 8 },
        _print: { display: 'none' },
      },
      content: { alignItems: 'flex-start', gap: 1, w: 'full' },
      label: { fontSize: { base: 'lg', md: '2xl' }, fontWeight: 'medium' },
      link: {
        display: 'block',
        w: 'full',
        color: 'white',
        _hover: { textDecoration: 'none' },
        _focusVisible: {
          outline: '2px solid',
          outlineColor: 'white',
          outlineOffset: '4px',
        },
      },
      wordmark: { w: 'full', h: 'auto' },
    },
  }),
  siteEventStream: defineSlotRecipe({
    slots: [
      'toggle',
      'panel',
      'header',
      'events',
      'empty',
      'footer',
      'shortcut',
      'card',
    ],
    base: {
      toggle: {
        position: 'fixed',
        bottom: 4,
        right: 4,
        zIndex: 'eventStreamToggle',
        borderWidth: '1px',
        borderColor: 'border',
        borderRadius: 'md',
        bg: 'bg',
        color: 'fg',
        _hover: { bg: 'bg.panel' },
      },
      panel: {
        animationName: {
          _open: 'slide-from-right-full',
          _closed: 'slide-to-right-full',
        },
        animationDuration: 'eventStreamPanel',
        animationTimingFunction: 'snappy',
        animationFillMode: 'both',
        _motionReduce: { animation: 'none' },
        position: 'fixed',
        top: 0,
        right: 0,
        bottom: 0,
        w: { base: 'full', md: 80 },
        bg: 'bg',
        borderLeftWidth: '1px',
        borderLeftColor: 'border',
        zIndex: 'eventStreamPanel',
        display: 'flex',
        flexDirection: 'column',
      },
      header: {
        h: 'siteHeader',
        flexShrink: 0,
        px: 4,
        borderBottomWidth: '1px',
        borderBottomColor: 'border',
        justifyContent: 'space-between',
        alignItems: 'center',
        bg: 'bg',
      },
      events: { flex: 1, overflowY: 'auto', p: 3, bg: 'eventStream.canvas' },
      empty: {
        h: 'full',
        alignItems: 'center',
        justifyContent: 'center',
        flexDirection: 'column',
        color: 'fg.muted',
        gap: 2,
      },
      footer: {
        p: 3,
        borderTopWidth: '1px',
        borderTopColor: 'border',
        bg: 'bg',
      },
      shortcut: { fontFamily: 'mono', bg: 'bg.panel', px: 1 },
      card: {
        p: 3,
        borderWidth: '2px',
        borderRadius: 'lg',
        boxShadow: 'sm',
        bg: 'bg',
        w: 'full',
        animationName: 'eventCardEnter',
        animationDuration: 'eventStreamCard',
        animationTimingFunction: 'ease-out',
        _motionReduce: { animation: 'none' },
      },
    },
  }),
}
