import { defineSlotRecipe } from '@chakra-ui/react'

// Site-specific chrome lives in the theme. Components keep content, behavior,
// and one-off layout props; Chakra's css prop consumes these slot recipes.
export const siteSlotRecipes = {
  siteDisclosure: defineSlotRecipe({
    slots: ['root', 'trigger', 'indicator', 'content'],
    base: {
      root: {
        borderWidth: '1px',
        borderColor: 'border',
        borderRadius: 'md',
        overflow: 'hidden',
      },
      trigger: {
        display: 'flex',
        w: 'full',
        px: 4,
        py: 3,
        gap: 2,
        alignItems: 'center',
        justifyContent: 'space-between',
        cursor: 'pointer',
        textAlign: 'left',
        _open: { bg: 'bg.muted' },
        _hover: { bg: 'bg.muted' },
        _focusVisible: {
          outline: '2px solid',
          outlineColor: 'fg.muted',
          outlineOffset: '-2px',
        },
      },
      indicator: {
        flexShrink: 0,
        boxSize: 5,
        color: 'fg.muted',
        transitionProperty: 'transform',
        transitionDuration: 'eventStreamPanel',
        transitionTimingFunction: 'snappy',
        _open: { transform: 'rotate(180deg)' },
        _motionReduce: { transition: 'none' },
      },
      content: {
        px: 4,
        py: 3,
        borderTopWidth: '1px',
        borderColor: 'border',
        _motionReduce: { animation: 'none' },
      },
    },
  }),
  siteFileTree: defineSlotRecipe({
    slots: ['root', 'folder', 'indicator', 'content', 'file'],
    base: {
      root: {
        my: 4,
        p: 4,
        borderRadius: 'lg',
        bg: 'fileTree.canvas',
        fontFamily: 'mono',
        fontSize: 'sm',
        overflowWrap: 'anywhere',
      },
      folder: {
        display: 'flex',
        alignItems: 'center',
        gap: 2,
        py: 0.5,
        w: 'full',
        textAlign: 'left',
        cursor: 'pointer',
        _hover: { color: 'site.link' },
        _focusVisible: {
          outline: '2px solid',
          outlineColor: 'fg.muted',
          outlineOffset: '2px',
        },
      },
      indicator: {
        boxSize: 3,
        fontSize: 'xs',
        flexShrink: 0,
        color: 'fg.muted',
        _open: { transform: 'rotate(90deg)' },
      },
      content: {
        pl: 6,
        borderLeftWidth: '1px',
        borderColor: 'border',
        ml: 1.5,
        _motionReduce: { animation: 'none' },
      },
      file: { display: 'flex', alignItems: 'center', gap: 2, py: 0.5 },
    },
  }),
  siteAnnouncement: defineSlotRecipe({
    slots: ['root', 'content', 'message', 'link', 'close'],
    base: {
      root: { py: 2, px: 4 },
      content: {
        maxW: '7xl',
        mx: 'auto',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 2,
      },
      message: { fontSize: 'sm', fontWeight: 'medium', textAlign: 'center' },
      link: {
        display: 'inline-flex',
        alignItems: 'center',
        gap: 1,
        textDecoration: 'underline',
        fontWeight: 'semibold',
        color: 'inherit',
        _hover: { opacity: 0.8 },
      },
      close: {
        flexShrink: 0,
        color: 'inherit',
        _hover: { bg: 'blackAlpha.100' },
      },
    },
    variants: {
      status: {
        info: {
          root: {
            colorPalette: 'blue',
            bg: 'colorPalette.solid',
            color: 'colorPalette.contrast',
          },
        },
        warning: {
          root: {
            colorPalette: 'yellow',
            bg: 'colorPalette.solid',
            color: 'colorPalette.contrast',
          },
        },
        success: {
          root: {
            colorPalette: 'green',
            bg: 'colorPalette.solid',
            color: 'colorPalette.contrast',
          },
        },
      },
    },
    defaultVariants: { status: 'info' },
  }),
  siteNavbar: defineSlotRecipe({
    slots: ['root', 'container', 'brand', 'navLink', 'githubTrigger'],
    base: {
      root: {
        position: 'sticky',
        top: 0,
        zIndex: 'siteHeader',
        h: 'siteHeader',
        borderBottomWidth: '1px',
        bg: 'bg',
      },
      container: { maxW: '7xl', h: 'full' },
      brand: {
        fontWeight: 'medium',
        fontSize: 'lg',
        _hover: { textDecoration: 'none' },
      },
      navLink: { color: 'fg.muted', _hover: { color: 'fg' } },
      githubTrigger: {
        color: 'fg.muted',
        minH: 11,
        minW: 11,
        _hover: { color: 'fg', bg: 'bg.panel' },
      },
    },
  }),
  siteFooter: defineSlotRecipe({
    slots: ['root', 'container', 'content', 'creditLink', 'licenseLink'],
    base: {
      root: {
        bg: 'bg',
        color: 'fg.muted',
        borderTopWidth: '1px',
        borderColor: 'border',
      },
      container: { maxW: '7xl', py: { base: 6, md: 8 } },
      content: {
        display: 'flex',
        flexDirection: { base: 'column', md: 'row' },
        alignItems: { base: 'flex-start', md: 'center' },
        justifyContent: 'space-between',
        gap: 3,
        fontSize: 'sm',
      },
      creditLink: { color: 'fg' },
      licenseLink: { color: 'fg', minH: 11, flexShrink: 0 },
    },
  }),
  communeFooter: defineSlotRecipe({
    slots: ['root', 'content', 'label', 'link', 'wordmark'],
    base: {
      root: {
        maxW: 'full',
        bg: 'black',
        color: 'white',
        pt: { base: 2, md: 8 },
        pb: { base: 4, md: 8 },
        _print: { display: 'none' },
      },
      content: { alignItems: 'flex-start', gap: 1, w: 'full' },
      label: { fontSize: { base: 'lg', md: '2xl' }, fontWeight: 'medium' },
      link: {
        display: 'block',
        w: 'full',
        color: 'white',
        _hover: { textDecoration: 'none' },
        _focusVisible: {
          outline: '2px solid',
          outlineColor: 'white',
          outlineOffset: '4px',
        },
      },
      wordmark: { w: 'full', h: 'auto' },
    },
  }),
  siteEventStream: defineSlotRecipe({
    slots: [
      'toggle',
      'panel',
      'header',
      'events',
      'empty',
      'footer',
      'shortcut',
      'card',
    ],
    base: {
      toggle: {
        position: 'fixed',
        bottom: 4,
        right: 4,
        zIndex: 'eventStreamToggle',
        borderWidth: '1px',
        borderColor: 'border',
        borderRadius: 'md',
        bg: 'bg',
        color: 'fg',
        _hover: { bg: 'bg.panel' },
      },
      panel: {
        animationName: {
          _open: 'slide-from-right-full',
          _closed: 'slide-to-right-full',
        },
        animationDuration: 'eventStreamPanel',
        animationTimingFunction: 'snappy',
        animationFillMode: 'both',
        _motionReduce: { animation: 'none' },
        position: 'fixed',
        top: 0,
        right: 0,
        bottom: 0,
        w: { base: 'full', md: 80 },
        bg: 'bg',
        borderLeftWidth: '1px',
        borderLeftColor: 'border',
        zIndex: 'eventStreamPanel',
        display: 'flex',
        flexDirection: 'column',
      },
      header: {
        h: 'siteHeader',
        flexShrink: 0,
        px: 4,
        borderBottomWidth: '1px',
        borderBottomColor: 'border',
        justifyContent: 'space-between',
        alignItems: 'center',
        bg: 'bg',
      },
      events: { flex: 1, overflowY: 'auto', p: 3, bg: 'eventStream.canvas' },
      empty: {
        h: 'full',
        alignItems: 'center',
        justifyContent: 'center',
        flexDirection: 'column',
        color: 'fg.muted',
        gap: 2,
      },
      footer: {
        p: 3,
        borderTopWidth: '1px',
        borderTopColor: 'border',
        bg: 'bg',
      },
      shortcut: { fontFamily: 'mono', bg: 'bg.panel', px: 1 },
      card: {
        p: 3,
        borderWidth: '2px',
        borderRadius: 'lg',
        boxShadow: 'sm',
        bg: 'bg',
        w: 'full',
        animationName: 'eventCardEnter',
        animationDuration: 'eventStreamCard',
        animationTimingFunction: 'ease-out',
        _motionReduce: { animation: 'none' },
      },
    },
  }),
}
