version: 2.1

jobs:
  build-test-package:
    docker:
      - image: cimg/node:22.15.1
    steps:
      - checkout

      - restore_cache:
          keys:
            - v2-root-dependencies-{{ checksum "yarn.lock" }}
            - v2-root-dependencies-

      - run:
          name: Install package dependencies
          command: yarn install --frozen-lockfile

      - save_cache:
          paths:
            - node_modules
          key: v2-root-dependencies-{{ checksum "yarn.lock" }}

      - restore_cache:
          keys:
            - v2-docs-dependencies-{{ checksum "docs/yarn.lock" }}
            - v2-docs-dependencies-

      - run:
          name: Install docs dependencies
          command: yarn --cwd docs install --frozen-lockfile

      - save_cache:
          paths:
            - docs/node_modules
          key: v2-docs-dependencies-{{ checksum "docs/yarn.lock" }}

      - run:
          name: Check formatting
          command: yarn format:check

      - run:
          name: Lint
          command: yarn lint

      - run:
          name: Test with coverage
          command: yarn test:ci

      - run:
          name: Verify packed package
          command: yarn release:smoke

      - run:
          name: Build documentation
          command: yarn --cwd docs build

      - run:
          name: Upload coverage to Coveralls
          command: cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

      - run:
          name: Upload coverage to Codecov
          command: bash <(curl -s https://codecov.io/bash)

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  test-package:
    jobs:
      - build-test-package
